# Generated by Django 5.1.1 on 2024-09-10 14:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillist',
            name='emails',
        ),
        migrations.AddField(
            model_name='emaillist',
            name='file',
            field=models.FileField(default='profile_pics/default.jpg', upload_to='email_lists/'),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
