# Generated by Django 5.1.1 on 2024-09-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0003_remove_email_email_list_emailcampaign'),
        ('tracker', '0002_alter_emailopen_tracking_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
