# Generated by Django 5.1.1 on 2024-10-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0004_delete_email'),
        ('mailmanager', '0002_alter_emailsetting_gmail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='camping_email',
            field=models.ManyToManyField(to='mailmanager.emailsetting'),
        ),
    ]
