# Generated by Django 5.1.1 on 2024-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetting',
            name='gmail_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
