# Generated by Django 5.0.3 on 2024-08-29 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emailservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('user_agent', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('isp', models.CharField(max_length=255)),
                ('tracking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailservice.email')),
            ],
        ),
    ]
